services:
  - type: web
    name: pdf-parser-ensemble
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 --graceful-timeout 300 --worker-class sync --max-requests 100 --max-requests-jitter 10 app:app
    envVars:
      - key: API_KEY
        generateValue: true
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
